server:
  port: 8000
spring:
  application:
    name: user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
eureka:
  client:
    server-url:
      # 测试失败，安全模式下注册失败
      #defaultZone: http://user:p123@cloud.eureka1:8761/eureka/,http://user:p123@cloud.eureka2:8762/eureka/
      defaultZone: http://cloud.eureka1:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExecutor: TRACE
info:
  app:
    name: "@project.artifactId@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"