spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      # 将自己注册到cloud.eureka2
      register-with-eureka: false
      fetch-registry: false
      # 测试失败，安全模式下注册失败
      #defaultZone: http://user:p123@cloud.eureka1:8761/eureka/,http://user:p123@cloud.eureka2:8762/eureka/
      # 测试完成，支持高可用模式
      #defaultZone: http://cloud.eureka1:8761/eureka/,http://cloud.eureka2:8762/eureka/
      # 日常开发使用模式
      defaultZone: http://cloud.eureka1:8761/eureka/
security:
  basic:
    # TODO 测试失败，client无法注册微服务
    enabled: false
  user:
    name: user
    password: p123
---
spring:
  # 指定profile=eureka1
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    # 指定profile=eureka1时，主机名为cloud.eureka1
    hostname: cloud.eureka1
---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: cloud.eureka2